services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Risenme@20
      MYSQL_DATABASE: student_perf
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    image: php:8.2-apache
    # This installs the mysqli extension needed for PHP to talk to MySQL
    command: sh -c "docker-php-ext-install mysqli && a2enmod rewrite && apache2-foreground"
    volumes:
      - ./Stud_Perf:/var/www/html
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_PORT: 5173
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_PORT: 5173
    networks:
      - app-network
    depends_on:
      php:
        condition: service_started
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: